name: Auto Sync Fork

on:
  schedule:
    - cron: '0 23 * * *' # 每天北京时间早上 7 点自动运行一次 (UTC时间 23:00)
  workflow_dispatch: # 支持你在网页上手动点击按钮立即运行

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予工作流写入你仓库的权限
    steps:
      - name: Sync upstream changes
        run: |
          gh repo sync buzhidaoqishamingzi-666/anti-AD -b master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
